services:
  - type: web
    name: melodrift-api
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /api/status
